apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coreapp
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: coreapp
    spec:
      containers:
        - name: coreapp
          image: docker.io/afghl/coreapp:latest
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: coreapp
spec:
  type: LoadBalancer
  selector:
    app: coreapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000